### ISSUE TITLE
Passing the page URL to the editor

### ISSUE THREAD

**Issue by mavit** [GhostText/GhostText#112]
I'm using `atomic-chrome` for Emacs, which is able to set the editing mode based on the page you’re visiting (e.g., GitHub flavoured MarkDown for `github.com`).  It does this by matching user-specified regular expressions against the URL provided by the browser.

However, I see that GhostText [passes only the hostname to the editor](https://github.com/GhostText/GhostText/blob/cec5a54926550a5b1b57898e7ea4f12d206c5451/browser/scripts/InputArea/TextChange.ts#L23), whereas Atomic Chrome does indeed appear to [pass the whole URL](https://github.com/tuvistavie/atomic-chrome/blob/f75128b2b00495c9e4096048c7325861b10950c3/src/content-script.js#L5).

Is there a reason for this?  I was going to submit a pull request to `atomic-chrome` for Emacs to expand the documentation to explain this difference, but I wonder if instead it makes more sense to change GhostText to pass the full URL?

**Comment by bfred-it** [comment]
As you said, you specify _GitHub flavoured MarkDown for `github.com`_, so that's why we don't pass the whole URL: the hostname is enough.

Either way, the original intention was to [move the syntax guesser to the browser](https://github.com/GhostText/GhostText/issues/65), which can figure out the desired language by looking at the dom, not just at the domain (e.g. you can write in any language on `github.com`'s CodeMirror).

However I don't have enough time to dedicate to GT to make/test the change and I don't feel comfortable changing the schema. #65 would be a better investment, or `atomic-chrome` could support the `hostname` as part of the original GhostText schema.

**Comment by To1ne** [comment]
I'm using atomic-chrome in Emacs, and I'm interested to save the text content to a file whenever I'm done editing. But I'd like to also store the URL with it, the full URL. This way I have a offline archive of my comments and can visit the associated page whenever I want.

What are the reasons not to have the full URL passed from GhostText to the editor?
