### ISSUE TITLE
Markdown is not rendered in bitbucket editor

### ISSUE THREAD

**Issue by liiight** [GhostText/GhostText#134]
# Setup

Browser: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Editor: Sublime text 3

# Description

Bitbucket has recently [changed](https://confluence.atlassian.com/bitbucket/updates-to-comment-and-description-editor-945114421.html) their comment editor and now it does no render markdown sent via Ghost text.

**Comment by bfred-it** [comment]
Yeah that now has become a plain `contentEditable` and they hacked on markdown support in it, somehow. GhostText doesn’t inject each keystroke separately so their new editor doesn’t handle them correctly. 

To do so GhostText would either have to change its protocol to transmit each character at a time or implement a diff in the browser so it can figure that out without changing all the editor extensions.

Ether way it’s a big undertaking and I don’t have time/desire to handle it. 

The good news is that you can now write HTML instead of markdown and since you’re in a text editor HTML shouldn’t be too difficult to write.

**Comment by bfred-it** [comment]
Actually it’s even harder than that because if you typed Markdown, it would be converted to HTML by BitBucket and you’d get HTML back in the editor, not Markdown.

Your best bet is #53 but that is also a big task that isn’t being done by anyone 😅

**Comment by liiight** [comment]
Yeah, I imagined their custom transformation would be hard to integrate, no worries. 

#53 sounds great but very ambitious indeed, not holding my breath for it 😄 

I'd like to take this opportunity to thank you for this amazing tool, I can't not use it once I discovered it. So thank you!
