### ISSUE TITLE
Extension out of date on Firefox for macOS?

### ISSUE THREAD

**Issue by torpesco** [GhostText/GhostText#177]
# Setup

Browser: Firefox 84.0.2 on macOS 10.15.7
Editor: Emacs

# Description

No way to configure keyboard shortcut. I see via discussion [in this PR](https://github.com/GhostText/GhostText/pull/159) that this should have been fixed a while ago, but the version of the extension I see available was last published in 2017: https://addons.mozilla.org/en-US/firefox/addon/ghosttext/

>Version
>    **17.12.11.910**
>Size
>    **62.22 KB**
>Last updated
>    **3 years ago (Dec 11, 2017)**

GhostText works for editing text using Emacs, but it's painful not having the shortcut. (I just switched from another browser.)

**Comment by fregante** [comment]
Mozilla Addons is an absolute joke. The 2019 version was approved and then rejected afterwards because I used a "library" (i.e. some CSS code from another repo) so six months later they pulled the version from the store. No further communication happened from them once I pointed this out, they just disabled the version.

Hopefully I'll get around to publishing the latest version soon but it needs some testing and bugfixes and I don't have that much time.

**Comment by fregante** [comment]
I pushed a new version, hopefully it will be accepted soon

**Comment by fregante** [comment]
I just noticed what the issue is. Actually the 2019 version that was rejected was an automated release, but it contained no updates. That issue was fixed because Firefox now lets you customize the shortcuts. Details in the readme: https://github.com/GhostText/GhostText#keyboard-shortcuts

**Comment by fregante** [comment]
I just noticed what the issue is. Actually the 2019 version that was rejected was an automated release, but it contained no updates. That issue was fixed because [Firefox now lets you customize the shortcuts](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox).

**Comment by torpesco** [comment]
Thanks! I hope it gets through Mozilla approval soon.
