### ISSUE TITLE
"Unexpected reserved word" in Chromium

### ISSUE THREAD

**Issue by bussnet** [GhostText/GhostText#87]
Hey guys.

I have Problems with the chrome extension on every page in Chromium 41.0.2250.0.

Got this on the console if I click the GhostEdit button and nothing happens.
```
 Uncaught SyntaxError: Unexpected reserved word
content.js:39 Got message: Object {action: "select-field", tabId: 2945}
content.js:150 GhostText: selectField()
extensions::uncaught_exception_handler:8 Error in event handler for runtime.onMessage: ReferenceError: GhostText is not defined
```
<img width="1672" alt="screenshot 2016-09-30 um 04 50 27" src="https://cloud.githubusercontent.com/assets/4171382/18979247/6c2139ec-86c9-11e6-96e8-413f49c2646b.png">

**Comment by bussnet** [comment]
worked after an upgrade to Chromium 53.0.2785.143, so maybe the extension can restrict to newer versions of chrome

**Comment by bfred-it** [comment]
Yeah, in v1.2.2 I switched to have our typescript files [compiled to ES6](https://github.com/GhostText/GhostText/blob/87c67a15f6d9f18c6b50889828e9bc83732aa6eb/tsconfig.json#L4) (classes). Classes have been available since Chrome 49, which is now 6 months old.

If you need to use version older than Chrome 49 you can use a previous version and compile using [these instructions](https://github.com/GhostText/GhostText/tree/master/browser#installation-of-the-development-version)

**Comment by bfred-it** [comment]
I added the restriction in v1.2.4 but I think it doesn't solve your issue since the store [discards older versions anyway](http://stackoverflow.com/a/10744580/288906)

**Comment by bussnet** [comment]
extrem fast support - great ;)
I installed the ghostText plugin from the chromestore some weeks ago, so it should be possible for others also.
